version: '3.8'

services:
  api:
    restart: always
    build:
      context: ./../../src/
      dockerfile: ./Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:5010/
      ConnectionStrings__ElderlyCare: Server=db;Database=elderly_care_local;Uid=root;Pwd=root;
    ports:
      - 5010:5010
    networks:
      - elderly_care_net
    depends_on:
      - db

networks:
  elderly_care_net:
    driver: bridge
