version: '3.8'

services:
  api:
    build:
      context: ../../src/
      dockerFile: ../../src/Api/Dockerfile.develop
    env_file: .env
    environment:
      ASPNETCORE_URLS: http://*:5010/
  depends_on:
    - db
