version: '3.2'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elderly_care_local
    ports:
      - 3306:3306
    networks:
      - elderly_care_net

networks:
  elderly_care_net:
    driver: bridge