version: '3.8'

services:
  web_app:
    restart: always
    build:
      context: ./../../src/
      dockerfile: ./WebApp/Dockerfile
    ports:
      - 3000:80
    networks:
      - elderly_care_net
    depends_on:
      - api

networks:
  elderly_care_net:
    driver: bridge