version: '3.8'

services:
  opcua_server:
    build:
      context: ./../../src/
      dockerfile: ./OpcuaServer/Dockerfile
    ports:
      - 4840:4840
    networks:
      - elderly_care_net

networks:
  elderly_care_net:
    driver: bridge