version: '3.8'

services:
  worker:
    restart: always
    build:
      context: ./../../src/
      dockerfile: ./Worker/Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:5020/
      ConnectionStrings__ElderlyCare: Server=db;Database=elderly_care_local;Uid=root;Pwd=root;
    ports:
      - 5020:5020
    networks:
      - elderly_care_net
    depends_on:
      - db

networks:
  elderly_care_net:
    driver: bridge