version: '3.8'

services:
  worker:
    build:
      context: ../../src/
      dockerFile: ../../src/Workers.RobotHandler/Dockerfile.develop
    env_file: .env
    environment:
      ASPNETCORE_URLS: http://*:5020/
  depends_on:
    - db